name: Publish GitHub Release

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: write

jobs:
  release:
    name: Publish GitHub Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          pattern: binary-*
          path: dist
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: List assets
        run: ls -lh dist

      - name: Publish / upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: dist/*
          fail_on_unmatched_files: true
